name: Scorer Action
description: Cacluates the score of an issue/pr
inputs:
  values:
    description: 'CSV of Reach/Impact/Confidence/Effort'
    required: true
outputs:
  score:
    value: ${{ steps.plus.outputs.result }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: bookmark
  color: purple